import './globals.css'
import '@repo/ui/styles.css'

import { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { GlobalProvider } from './global-provider'
import { GlobalTheme } from './global-theme'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <GlobalProvider>
      <html lang="en">
        <body className={inter.className}>
          <GlobalTheme>{children}</GlobalTheme>
        </body>
      </html>
    </GlobalProvider>
  )
}
