import './globals.css'

import { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Header } from '@/features/header'

import { Providers } from './providers'
import { Theme } from './theme'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <Providers>
          <Theme>
            <Header />
            {children}
          </Theme>
        </Providers>
      </body>
    </html>
  )
}
